### ISSUE TITLE
NIST site fails during gov shutdown > Need good error message

### ISSUE THREAD

**Issue by rsvp** [hmason/randomness_beacon#1]
The Beacon appears to be a non-essential gov service, and so its web server returns generic nonsense page. Something like this might help generally in the future:

```
if not result.find('seedValue'):
            raise IOError, "NIST site did not return result in expected format."
```

**Comment by hmason** [comment]
Done!

**Comment by rsvp** [comment]
I got fed up with the gov shutdown so I wrote something which uses the entropy generated within the kernel. Please check out:  https://gist.github.com/rsvp/7002774 

$ randout 512 --hex

# example which may be helpful for you :-)
